[package]
name = "zip-investigator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.6.6"
walkdir = "2.4.0"
humansize = "2.1.3"
